apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: {{ namespace }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
     metadata:
        labels:
          app: frontend
     spec:
        containers:
        - image: nginx:1.17
          
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ namespace }}
spec:
  ports:
  - nodePort: {{ port }}
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: frontend
  sessionAffinity: None
  type: NodePort
